<?php

namespace AppBundle\Repository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQbByUser($userId)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.createdBy', 'c')
            ->where('c.id = :userId')
            ->setParameter('userId', $userId)
            ->orderBy( 's.updatedAt', 'DESC')
            ;

        return $qb;
    }
}
